In [4]:
import torch.utils.data as Data
import torch
import numpy as np

num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

batch_size = 32

dataset = Data.TensorDataset(features,labels)

In [6]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        j = torch.LongTensor(indices[i:min(i + batch_size, num_examples)])
        yield features.index_select(0, j), labels.index_select(
            0, j)


In [9]:
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)

for X, y in data_iter:
    print(X, y)
    break

tensor([[ 1.4302, -0.7976],
        [-1.3555,  0.1909],
        [-0.4244, -0.1911],
        [-0.5975,  0.1618],
        [ 0.3236, -0.1173],
        [ 0.1115, -1.2463],
        [ 1.3928, -1.2630],
        [ 0.0033, -2.4750],
        [ 1.7536,  0.8324],
        [ 0.0762,  1.7674],
        [-0.9593,  1.0579],
        [-0.7738, -0.0482],
        [-1.2796,  0.2263],
        [-1.3886,  0.6845],
        [-0.9094,  0.5778],
        [-2.0111,  0.2090],
        [-0.2983, -0.0621],
        [-1.0997, -0.7513],
        [ 0.4069,  0.3781],
        [-0.0988, -1.4225],
        [-1.3866,  0.0036],
        [ 1.1796,  2.1882],
        [-1.8575, -0.5420],
        [-1.8676, -0.9497],
        [ 0.8633, -0.9826],
        [-1.5069, -1.2985],
        [ 0.6443,  0.9282],
        [ 0.1459, -0.2731],
        [ 0.0057, -0.0818],
        [ 1.5517,  0.4084],
        [-1.2332,  0.8785],
        [ 1.6544,  0.1324]]) tensor([ 9.7617,  0.8434,  3.9912,  2.4545,  5.2487,  8.6764, 11.2702, 12.6339,
         4.8729, -1.636

In [12]:
import torch.nn as nn

class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)
    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y
net = LinearNet(num_inputs)
print(net) # 使用print可以打印出网络的结构

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [13]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.5767, -0.1550]], requires_grad=True)
Parameter containing:
tensor([0.2703], requires_grad=True)


In [14]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)
loss = nn.MSELoss()

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [17]:
num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad() # 梯度清零，等价于net.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))

epoch 1, loss: 0.327935
epoch 2, loss: 0.003105
epoch 3, loss: 0.000414
